TEMPLATE = """\
You are a expert developer and you are going to develop a prober of a model given a \
training repo.

A prober is one or some evaluation protocol or metrics that may indicate the a \
problem of a trained model. The prober will be a class or function that generate \
metrics, charts and figures that indicate the problem given the trained model and \
eval dataset.

# Instruction

- Read the development plan in `.codex/development_plan.md`, you are going to \
implement the plan for adding a prober in the training repo.

# Requirements

- The prober code MUST be implemented in `prober.py`.
- Locate model training code and make sure the prober code is properly inserted into the training code \
and called after training during evaluation phase.
- Make sure the result metrics and figures generated by prober is tracked through \
`aim.sdk.agent.research_agent_logger`.
- Make sure the result metrics from test result has the name starts with `agent_log_test_`.
- Make sure the result figures from prober has the name starts with `agent_log_prober_ and clearly visualize the evaluation`.
- Make sure you fully reuse the existing components of existing code.
- Make your implementation as efficient as possible.
- Make sure you apply the best software engieering pratice.
- Make sure you make minimum change to the code.
- Make sure you the modified training repo is easy to understand.

Now start generate\
"""
